server:
  port: 8761

spring:
  application:
    name: discovery-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  username: ${EUREKA_USERNAME:eureka}
  password: ${EUREKA_PASSWORD:password}

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0